#
#                <-- KitPvp Config -->
#            Leave no values null and make
#              sure all values are valid.
#

# MySql connection options.
database:
  # Database address.
  address: "127.0.0.1"

  # Database port.
  port: 3306

  # Database name.
  name: kitpvp

  # Database user.
  user: root

  # Database password.
  password: godgod

# Options related to world and natural player behaviour.
world:
  # Whether or not rain is allowed on the server.
  allow-rain: false

  # Whether or not hunger is allowed on the server.
  allow-hunger: false
