# MySql connection options.
database:
  # Database address.
  address: "127.0.0.1"

  # Database port.
  port: 3306

  # Database name.
  name: "kitpvp"

  # Database user.
  user: "root"

  # Database password.
  password: "godgod"
