name: KitPvp
main: net.nikdev.kitpvp.KitPvp
version: 1.0-SNAPSHOT
author: NickTheDev
website: http://nikdev.net/
commands:
  kitpvp:
    aliases: [kp, kits]
    description: KitPvp's base command.
permissions:
  kitpvp.*:
    children:
      kitpvp.wand: true
      kitpvp.setlocations: true
      kitpvp.edit-terrain: true
  kitpvp.wand:
    description: Allows a player to use /kitpvp wand.
  kitpvp.setlocations:
    description: Allows a player to use /kitpvp setlocations.
  kitpvp.edit-terrain:
    description: Allows a player to break and place blocks.